export const UPDATE_IG = 'UPDATE_IG';
export const REMOVE_IG = 'REMOVE_IG';
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_INGREDIENTS_PRICE = "SET_INGREDIENTS_PRICE";
export const INGREDIENTS_LOADING = "INGREDIENTS_LOADING";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = "PURCHASE_INIT";
