export const UPDATE_IG = 'UPDATE_IG';
export const REMOVE_IG = 'REMOVE_IG';
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_INGREDIENTS_PRICE = "SET_INGREDIENTS_PRICE";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
